# Generated by Django 5.0.14 on 2025-11-04 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Factor de multiplicación para cálculo de costos",
                        max_digits=5,
                        verbose_name="Multiplicador de Tarifa",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código de la operación (ej: CPT, ICD)",
                        max_length=50,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "base_points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Puntos base para cálculo de costo",
                        max_digits=10,
                        verbose_name="Puntos Base",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "complexity",
                    models.IntegerField(
                        default=1,
                        help_text="Nivel de complejidad (1-5)",
                        verbose_name="Complejidad",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="medico.specialty",
                        verbose_name="Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación",
                "verbose_name_plural": "Operaciones",
                "ordering": ["specialty", "name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalOperationRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor monetario de cada punto",
                        max_digits=10,
                        verbose_name="Valor del Punto",
                    ),
                ),
                (
                    "currency_per_point",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad en moneda local por punto",
                        max_digits=10,
                        verbose_name="Moneda por Punto",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_rates",
                        to="medico.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_rates",
                        to="medico.operation",
                        verbose_name="Operación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa Hospital-Operación",
                "verbose_name_plural": "Tarifas Hospital-Operación",
                "ordering": ["hospital", "operation"],
                "unique_together": {("hospital", "operation")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="medico.operation",
                        verbose_name="Operación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="medico_favo_user_id_919855_idx",
                    )
                ],
                "unique_together": {("user", "operation")},
            },
        ),
        migrations.CreateModel(
            name="CalculationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Calculado"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cálculo"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="medico.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="medico.operation",
                        verbose_name="Operación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cálculo",
                "verbose_name_plural": "Historial de Cálculos",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "calculated_at"],
                        name="medico_calc_user_id_c8effa_idx",
                    ),
                    models.Index(
                        fields=["operation"], name="medico_calc_operati_bb97d1_idx"
                    ),
                    models.Index(
                        fields=["hospital"], name="medico_calc_hospita_ae0e41_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["code"], name="medico_oper_code_6602aa_idx"),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["specialty"], name="medico_oper_special_7f641b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["name"], name="medico_oper_name_cb89a3_idx"),
        ),
    ]
