# Generated by Django 5.0.14 on 2025-11-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurgicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Paciente"
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="Número de identificación del paciente",
                        max_length=50,
                        null=True,
                        verbose_name="Cédula/ID del Paciente",
                    ),
                ),
                (
                    "patient_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edad del Paciente"
                    ),
                ),
                (
                    "patient_gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                ("surgery_date", models.DateField(verbose_name="Fecha de Cirugía")),
                (
                    "surgery_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Cirugía"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Realizada"),
                            ("billed", "Facturada"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones sobre el caso",
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="Diagnóstico preoperatorio",
                        null=True,
                        verbose_name="Diagnóstico",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgical_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_cases",
                        to="medico.hospital",
                        verbose_name="Hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso Quirúrgico",
                "verbose_name_plural": "Casos Quirúrgicos",
                "ordering": ["-surgery_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surgery_code",
                    models.CharField(
                        help_text="Código del procedimiento",
                        max_length=50,
                        verbose_name="Código de Cirugía",
                    ),
                ),
                (
                    "surgery_name",
                    models.CharField(
                        max_length=500, verbose_name="Nombre del Procedimiento"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        help_text="Grupo o categoría del procedimiento",
                        max_length=100,
                        null=True,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "rvu",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Relative Value Units",
                        max_digits=10,
                        verbose_name="RVU",
                    ),
                ),
                (
                    "hospital_factor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Multiplicador del hospital",
                        max_digits=5,
                        verbose_name="Factor del Hospital",
                    ),
                ),
                (
                    "calculated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor monetario del procedimiento",
                        max_digits=12,
                        verbose_name="Valor Calculado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas del Procedimiento"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden del procedimiento en el caso",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="medico.surgicalcase",
                        verbose_name="Caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimiento del Caso",
                "verbose_name_plural": "Procedimientos de Casos",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["created_by", "surgery_date"],
                name="medico_surg_created_2a8d75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["hospital", "surgery_date"],
                name="medico_surg_hospita_94bac7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(fields=["status"], name="medico_surg_status_805f06_idx"),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["patient_id"], name="medico_surg_patient_f02d4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseprocedure",
            index=models.Index(
                fields=["case", "order"], name="medico_case_case_id_b50179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseprocedure",
            index=models.Index(
                fields=["surgery_code"], name="medico_case_surgery_baa331_idx"
            ),
        ),
    ]
