# Generated by Django 5.0.14 on 2025-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0003_favoritehospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseprocedure",
            name="calculated_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor monetario del procedimiento",
                max_digits=15,
                verbose_name="Valor Calculado",
            ),
        ),
    ]
