# Generated by Django 5.2.7 on 2025-12-22 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_caseprocedure_calculated_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseprocedure',
            options={'ordering': ['case', 'order'], 'verbose_name': 'Procedimiento del Caso', 'verbose_name_plural': 'Procedimientos del Caso'},
        ),
        migrations.RemoveIndex(
            model_name='surgicalcase',
            name='medico_surg_patient_f02d4a_idx',
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='is_billed',
            field=models.BooleanField(default=False, help_text='Indica si la cirugía ya fue facturada', verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='is_operated',
            field=models.BooleanField(default=False, help_text='Indica si la cirugía ya fue realizada', verbose_name='Operado'),
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Indica si la cirugía ya fue cobrada', verbose_name='Cobrado'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='calculated_value',
            field=models.DecimalField(decimal_places=2, help_text='RVU × Factor del Hospital', max_digits=12, verbose_name='Valor Calculado'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='hospital_factor',
            field=models.DecimalField(decimal_places=2, help_text='Multiplicador del hospital para este procedimiento', max_digits=5, verbose_name='Factor del Hospital'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden del procedimiento en el caso', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='surgery_code',
            field=models.CharField(max_length=50, verbose_name='Código de Cirugía'),
        ),
        migrations.AlterField(
            model_name='caseprocedure',
            name='surgery_name',
            field=models.CharField(max_length=500, verbose_name='Nombre de la Cirugía'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del Paciente'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género del Paciente'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Número de identificación o expediente del paciente', max_length=100, null=True, verbose_name='ID del Paciente'),
        ),
        migrations.AlterField(
            model_name='surgicalcase',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('completed', 'Completado'), ('billed', 'Facturado'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='caseprocedure',
            index=models.Index(fields=['specialty'], name='medico_case_special_e42d08_idx'),
        ),
        migrations.AddIndex(
            model_name='surgicalcase',
            index=models.Index(fields=['surgery_date'], name='medico_surg_surgery_0f6456_idx'),
        ),
        migrations.AddIndex(
            model_name='surgicalcase',
            index=models.Index(fields=['is_operated'], name='medico_surg_is_oper_8b1993_idx'),
        ),
        migrations.AddIndex(
            model_name='surgicalcase',
            index=models.Index(fields=['is_billed'], name='medico_surg_is_bill_0194b5_idx'),
        ),
        migrations.AddIndex(
            model_name='surgicalcase',
            index=models.Index(fields=['is_paid'], name='medico_surg_is_paid_8211c0_idx'),
        ),
    ]
