# Generated by Django 5.2.7 on 2025-12-30 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_caseprocedure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalcase',
            name='assistant_doctor',
            field=models.ForeignKey(blank=True, help_text='Referencia a un colega registrado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_cases', to=settings.AUTH_USER_MODEL, verbose_name='Médico Ayudante (Colega)'),
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='assistant_doctor_name',
            field=models.CharField(blank=True, help_text='Nombre manual del médico ayudante (si no es un colega registrado)', max_length=255, null=True, verbose_name='Nombre del Médico Ayudante'),
        ),
        migrations.AddIndex(
            model_name='surgicalcase',
            index=models.Index(fields=['assistant_doctor'], name='medico_surg_assista_137668_idx'),
        ),
    ]
