# Generated by Django 5.2.7 on 2025-12-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_surgicalcase_assistant_doctor_and_more'),
    ]

    operations = [
    ]
