# Generated by Django 5.2.7 on 2026-01-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_sync_assistant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalcase',
            name='assistant_accepted',
            field=models.BooleanField(blank=True, default=None, help_text='Indica si el médico ayudante aceptó participar en este caso', null=True, verbose_name='Ayudante Aceptó'),
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='assistant_notified_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se notificó al ayudante sobre este caso', null=True, verbose_name='Fecha de Notificación al Ayudante'),
        ),
    ]
