# Generated by Django 5.0.14 on 2026-01-07 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0010_add_surgery_end_time_and_calendar_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="surgicalcase",
            name="calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="ID del evento sincronizado con Google Calendar",
                max_length=255,
                null=True,
                verbose_name="ID del Evento en Google Calendar",
            ),
        ),
        migrations.AlterField(
            model_name="surgicalcase",
            name="surgery_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Fin de Cirugía"
            ),
        ),
        migrations.AlterField(
            model_name="surgicalcase",
            name="surgery_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Inicio de Cirugía"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["calendar_event_id"], name="medico_surg_calenda_562993_idx"
            ),
        ),
    ]
