# Generated by Django 5.0.14 on 2026-01-21 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0011_alter_surgicalcase_calendar_event_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="surgicalcase",
            name="medico_surg_status_805f06_idx",
        ),
        migrations.RemoveIndex(
            model_name="surgicalcase",
            name="medico_surg_surgery_0f6456_idx",
        ),
        migrations.RemoveIndex(
            model_name="surgicalcase",
            name="medico_surg_assista_137668_idx",
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["status", "surgery_date"], name="medico_surg_status_a41d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["assistant_doctor", "assistant_accepted"],
                name="medico_surg_assista_ece26f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["created_at"], name="medico_surg_created_2e8c93_idx"
            ),
        ),
    ]
