# Generated by Django 5.0.14 on 2026-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0012_remove_surgicalcase_medico_surg_status_805f06_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseprocedure",
            name="calculated_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="RVU × Factor del Hospital",
                max_digits=15,
                verbose_name="Valor Calculado",
            ),
        ),
    ]
