#!/usr/bin/env python
"""
Convierte un dump de PostgreSQL a formato SQLite
Elimina referencias al esquema 'public' y ajusta sintaxis
"""

import re
import sys

def convert_postgres_to_sqlite(input_file, output_file):
    """Convierte un dump de PostgreSQL a SQLite"""
    
    print(f"🔄 Convirtiendo {input_file} a formato SQLite...")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Eliminar comandos específicos de PostgreSQL
    postgres_commands = [
        r'SET statement_timeout.*?;',
        r'SET lock_timeout.*?;',
        r'SET idle_in_transaction_session_timeout.*?;',
        r'SET transaction_timeout.*?;',
        r'SET client_encoding.*?;',
        r'SET standard_conforming_strings.*?;',
        r'SELECT pg_catalog\.set_config.*?;',
        r'SET check_function_bodies.*?;',
        r'SET xmloption.*?;',
        r'SET client_min_messages.*?;',
        r'SET row_security.*?;',
        r'SET default_tablespace.*?;',
        r'SET default_table_access_method.*?;',
        r'--\s*PostgreSQL database dump.*?\n',
        r'--\s*Dumped from database.*?\n',
        r'--\s*Dumped by pg_dump.*?\n',
    ]
    
    for pattern in postgres_commands:
        content = re.sub(pattern, '', content, flags=re.IGNORECASE | re.DOTALL)
    
    # Reemplazar referencias al esquema public
    content = re.sub(r'\bpublic\.', '', content)
    content = re.sub(r'Schema: public;', '', content)
    content = re.sub(r'Owner: postgres', '', content)
    
    # Reemplazar ALTER TABLE ... OWNER TO postgres
    content = re.sub(r'ALTER TABLE\s+\w+\s+OWNER TO postgres;', '', content)
    
    # Convertir SEQUENCES a AUTOINCREMENT de SQLite
    # Eliminar definiciones de secuencias
    content = re.sub(
        r'ALTER TABLE \w+ ALTER COLUMN \w+ ADD GENERATED BY DEFAULT AS IDENTITY \([\s\S]*?\);',
        '',
        content
    )
    
    # Convertir tipos de datos de PostgreSQL a SQLite
    conversions = {
        r'character varying\((\d+)\)': r'VARCHAR(\1)',
        r'character varying': 'VARCHAR',
        r'bigint': 'INTEGER',
        r'integer': 'INTEGER',
        r'smallint': 'INTEGER',
        r'timestamp with time zone': 'DATETIME',
        r'timestamp without time zone': 'DATETIME',
        r'boolean': 'INTEGER',
        r'text': 'TEXT',
        r'numeric\(\d+,\d+\)': 'REAL',
        r'numeric': 'REAL',
    }
    
    for pg_type, sqlite_type in conversions.items():
        content = re.sub(pg_type, sqlite_type, content, flags=re.IGNORECASE)
    
    # Convertir CREATE TABLE
    content = re.sub(r'CREATE TABLE (\w+)', r'CREATE TABLE IF NOT EXISTS \1', content)
    
    # Eliminar comandos COPY (datos masivos de PostgreSQL)
    content = re.sub(r'COPY \w+ .*? FROM stdin;[\s\S]*?\\\.', '', content)
    
    # Convertir ALTER TABLE ... ADD CONSTRAINT a CREATE INDEX o UNIQUE
    content = re.sub(
        r'ALTER TABLE ONLY (\w+)\s+ADD CONSTRAINT (\w+) PRIMARY KEY \((.*?)\);',
        r'CREATE UNIQUE INDEX IF NOT EXISTS \2 ON \1(\3);',
        content
    )
    
    # Eliminar ALTER TABLE ONLY
    content = re.sub(r'ALTER TABLE ONLY', 'ALTER TABLE', content)
    
    # Eliminar comentarios de Owner
    content = re.sub(r'--\s*Name:.*?Owner:.*?\n', '', content)
    
    # Eliminar líneas vacías múltiples
    content = re.sub(r'\n\s*\n\s*\n+', '\n\n', content)
    
    # Agregar BEGIN y COMMIT para transacción
    sqlite_content = "BEGIN TRANSACTION;\n\n" + content + "\n\nCOMMIT;\n"
    
    # Escribir archivo de salida
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(sqlite_content)
    
    print(f"✅ Archivo convertido guardado en: {output_file}")
    print(f"📊 Tamaño original: {len(content)} caracteres")
    print(f"📊 Tamaño convertido: {len(sqlite_content)} caracteres")
    
    return output_file

if __name__ == '__main__':
    input_file = 'backend/MeDico-2025_11_09_16_45_28-dump.sql'
    output_file = 'backend/MeDico-SQLite-dump.sql'
    
    try:
        convert_postgres_to_sqlite(input_file, output_file)
        print("\n🎉 ¡Conversión completada!")
        print(f"\nPara importar a SQLite, ejecuta:")
        print(f"   sqlite3 db.sqlite3 < {output_file}")
        print(f"\nO usa Python:")
        print(f"   python -c \"import sqlite3; conn = sqlite3.connect('db.sqlite3'); conn.executescript(open('{output_file}', 'r', encoding='utf-8').read()); conn.commit(); conn.close()\"")
    except FileNotFoundError:
        print(f"❌ Error: No se encontró el archivo {input_file}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
