# Generated by Django 5.2.7 on 2025-12-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'User')], default=1, help_text='Rol del usuario en el sistema (0=Admin, 1=User)', verbose_name='Rol'),
        ),
    ]
