# Generated by Django 5.2.7 on 2025-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medio_auth', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió el último token de verificación', null=True, verbose_name='Fecha de Envío del Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el email del usuario ha sido verificado', verbose_name='Email Verificado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token único para verificar el email del usuario', max_length=100, null=True, verbose_name='Token de Verificación de Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta ha sido verificada por un administrador', verbose_name='Cuenta Verificada por Admin'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verification_token'], name='medio_auth__email_v_ad3a77_idx'),
        ),
    ]
