# Generated by Django 5.2.7 on 2025-12-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_auth', '0003_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_code',
            field=models.CharField(blank=True, help_text='Código único para compartir con otros médicos', max_length=8, null=True, unique=True, verbose_name='Código de Colega'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', help_text='Plan actual del usuario', max_length=10, verbose_name='Plan de Suscripción'),
        ),
    ]
