# Generated by Django 5.2.7 on 2025-12-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nombre comercial del cliente', max_length=200, verbose_name='Nombre de la Empresa')),
                ('contact_name', models.CharField(blank=True, help_text='Persona de contacto', max_length=200, null=True, verbose_name='Nombre de Contacto')),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('plan', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro')], default='bronze', max_length=10, verbose_name='Plan Contratado')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Cantidad pagada en moneda local', max_digits=10, verbose_name='Monto Pagado')),
                ('currency', models.CharField(default='GTQ', help_text='Código de moneda (USD, GTQ, etc.)', max_length=3, verbose_name='Moneda')),
                ('start_date', models.DateField(help_text='Inicio del periodo de publicidad', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Fin del periodo de publicidad', verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente'), ('expired', 'Expirado')], default='active', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre el cliente', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Nombre interno para identificar el anuncio', max_length=200, verbose_name='Nombre de la Campaña')),
                ('title', models.CharField(blank=True, help_text='Título visible del anuncio (opcional)', max_length=200, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción del anuncio (opcional)', null=True, verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Imagen o GIF del anuncio', upload_to='advertisements/%Y/%m/', verbose_name='Imagen/GIF')),
                ('image_alt_text', models.CharField(blank=True, help_text='Descripción de la imagen para accesibilidad', max_length=200, null=True, verbose_name='Texto Alternativo')),
                ('redirect_url', models.URLField(help_text='URL a la que se redirige al hacer click', verbose_name='URL de Redirección')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Abrir en Nueva Pestaña')),
                ('placement', models.CharField(choices=[('home_banner', 'Banner Principal (Home)'), ('sidebar', 'Barra Lateral'), ('footer', 'Footer'), ('popup', 'Popup'), ('between_content', 'Entre Contenido')], default='home_banner', help_text='Dónde se mostrará el anuncio', max_length=20, verbose_name='Ubicación')),
                ('priority', models.IntegerField(default=0, help_text='Mayor número = mayor prioridad (0-100)', verbose_name='Prioridad')),
                ('start_date', models.DateField(help_text='Cuándo empieza a mostrarse', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Cuándo deja de mostrarse', verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Finalizado'), ('draft', 'Borrador')], default='draft', max_length=10, verbose_name='Estado')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha mostrado', verbose_name='Impresiones')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Número de clicks recibidos', verbose_name='Clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertising.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='advertising_status_50bf91_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['plan'], name='advertising_plan_487269_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['start_date', 'end_date'], name='advertising_start_d_54662b_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'placement'], name='advertising_status_b65477_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date', 'end_date'], name='advertising_start_d_2908f8_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['client', 'status'], name='advertising_client__9d611b_idx'),
        ),
    ]
