# Generated by Django 5.0.14 on 2026-01-20 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=cloudinary.models.CloudinaryField(
                help_text="Imagen o GIF del anuncio",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
